version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mysql
    restart: always
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  fastapi:
    build: .
    container_name: fastapi
    restart: always
    env_file: .env
    depends_on:
      - db
    ports:
      - "${FASTAPI_PORT}:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${MYSQL_DATABASE}
      FASTAPI_PORT: ${FASTAPI_PORT}

volumes:
  mysql_data:
