"""new enum

Revision ID: 5fbba5385e6c
Revises: f1ea508976f6
Create Date: 2025-09-14 21:53:31.035470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5fbba5385e6c'
down_revision: Union[str, Sequence[str], None] = 'f1ea508976f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('tipo', mysql.ENUM('gato', 'cachorro', 'cavalo', 'lagarto'), nullable=False),
    sa.Column('raca', mysql.ENUM('siamese', 'persa', 'maine_coon', 'labrador', 'bulldog', 'poodle', 'andaluz', 'arabe', 'quarto_de_milha', 'iguana', 'dragao_barbado', 'gecko'), nullable=False),
    sa.Column('cor', mysql.ENUM('branco', 'preto', 'cinza', 'marrom', 'amarelo', 'laranja'), nullable=False),
    sa.Column('castrado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
