"""create pets table

Revision ID: f1ea508976f6
Revises: 
Create Date: 2025-09-14 21:37:37.928382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f1ea508976f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('gato', 'cachorro', 'cavalo', 'lagarto', name='tipoanimalenum'), nullable=False),
    sa.Column('raca', sa.Enum('siamese', 'persa', 'maine_coon', 'labrador', 'bulldog', 'poodle', 'andaluz', 'arabe', 'quarto_de_milha', 'iguana', 'dragao_barbado', 'gecko', name='racaanimalenum'), nullable=False),
    sa.Column('cor', sa.Enum('branco', 'preto', 'cinza', 'marrom', 'amarelo', 'laranja', name='coranimalenum'), nullable=False),
    sa.Column('castrado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
