name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FASTAPI_PORT: 8000

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASS }}
          MYSQL_DATABASE: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -prootpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        
    env:
      DB_USER: root
      DB_PASS: ${{ secrets.DB_PASS }}
      DB_NAME: ${{ secrets.DB_NAME }} 
      DB_HOST: mysql
      DB_PORT: 3306

    steps:
  
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Run Alembic migrations
        env:
          SQLALCHEMY_URL: mysql+pymysql://${{ secrets.DB_USER }}:${{ secrets.DB_PASS }}@mysql:3306/${{ secrets.DB_NAME }}
        run: alembic upgrade head

      - name: Run tests
        run: |
          pytest --disable-warnings -v
